package com.teste.barbearia.model.enuns;

public enum Mensagens {
  SUCESSO_REMOVER_CLIENTE("Cliente removido com sucesso!"),
  SUCESSO_REMOVER_PRESTADOR("Prestador removido com sucesso!"),
  ERRO_CPF_JA_EXISTE("ESTE CPF JA EXISTE"),
  ERRO_INPUT_CLIENTE_VAZIO("O INPUT DEVE CONTER CPF E NOME DO CLIENTE"),
  ERRO_INPUT_PRESTADOR_VAZIO("O INPUT DEVE CONTER CPF E NOME DO PRESTADOR"),
  ERRO_CPF_INVALIDO("CPF INVALIDO"),
  ERRO_CPF_NAO_EXISTE("O CPF NAO EXISTE"),
  ERRO_ID_NAO_EXISTE("O ID INFORMADO NAO EXISTE"),
  ERRO_MES_INVALIDO("MES INVALIDO"),
  ERRO_PRESTADOR_INVALIDO("PRESTADOR INVALIDO"),
  ERRO_AGENDAMENTO_PASSADO("IMPOSSIVEL AGENDAR PARA O PASSADO"),
  ERRO_AGENDAMENTO_MARCADO_MESMO_HORARIO_CLIENTE("CLIENTE JA TEM AGENDAMENTO MARCADO PARA O MESMO DIA E HORARIO"),
  ERRO_HORARIO_INVALIDO("HORARIO INVALIDO"),
  ERRO_CLIENTE_INVALIDO("CLIENTE INVALIDO"),
  ERRO_DATA_INVALIDA("DATA INVALIDA"),
  ERRO_AGENDAMENTO_NAO_EXISTE("AGENDAMENTO NAO EXISTE"),
  ERRO_FALTA_ID_CPF("ID OU CPF PRECISAM SER PASSADOS");
  
  
  private String mensagem;
  Mensagens(String mensagem){
    this.mensagem = mensagem;
  }
  public String getMensagem() {
    return this.mensagem;
  }
}
